declare module '@govbr-ds/core/dist/partial/js/behavior/collapse';
declare module '@govbr-ds/core/dist/components/select/select';
declare module '@govbr-ds/core/dist/components/upload/upload';
declare module '@govbr-ds/core/dist/components/table/table';
declare module '@govbr-ds/core/dist/components/step/step';
declare module '@govbr-ds/core/dist/components/textarea/textarea';
declare module '@govbr-ds/core/dist/components/checkbox/checkbox';

// CSS Modules
declare module '@govbr-ds/core/dist/components/button/button.min.css';
declare module '@govbr-ds/core/dist/components/select/select.min.css';
declare module '@govbr-ds/core/dist/components/input/input.min.css';
declare module '@govbr-ds/core/dist/components/item/item.min.css';
declare module '@govbr-ds/core/dist/components/radio/radio.min.css';
declare module '@govbr-ds/core/dist/components/list/list.min.css';
declare module '@govbr-ds/core/dist/components/message/message.min.css';
declare module '@govbr-ds/core/dist/components/loading/loading.min.css';
declare module '@govbr-ds/core/dist/components/textarea/textarea.min.css';
declare module '@govbr-ds/core/dist/components/checkbox/checkbox.min.css';
declare module '@govbr-ds/core/dist/components/divider/divider.min.css';
declare module '@govbr-ds/core/dist/components/card/card.min.css';
declare module '@govbr-ds/core/dist/components/modal/modal.min.css';
declare module '@govbr-ds/core/dist/components/scrim/scrim.min.css';
