name: storybook-deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
    push:
        branches: ['master', 'dev']
    pull:
        branches: ['master', 'dev']

    workflow_dispatch:
jobs:
    quality:
        runs-on: ubuntu-latest
        environment: 
            name: development
        steps:
            - name: repo-checkout
              uses: actions/checkout@v4
            - name: node-setup
              uses: actions/setup-node@v4
              with:
               node-version: '20'
            - run: npm install
            - run: npm run test       