name: release

permissions:
    contents: write
    pages: write
    id-token: write

on:
    push:
        branches: ['master']

jobs:
    release:
        runs-on: 'ubuntu-latest'
        steps:
            - name: repo-checkout
              uses: actions/checkout@v4
            - name: node-setup
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm ci
            - run: npm run build
            - name: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run semantic-release
